import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import fs from "fs";
import { parseMarkdown } from "../components/parseMarkdown";

const Home: NextPage = ({ sortedArticles }: any) => {
  return (
    <div className={"container"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>header</h1>

        {sortedArticles.map((article: any) => {
          return (
            <li key={article.slug}>
              <a href={"/blog/" + article.slug}>{article.slug}</a>
            </li>
          );
        })}
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const files = fs.readdirSync("posts");
  const articles = files.map((file) => parseMarkdown(file).metadata);
  const sortedArticles = articles.sort((a, b) => new Date(b.date).valueOf() - new Date(a.date).valueOf())

  return {
    props: {
      sortedArticles
    },
  };
};

export default Home;
