import type { NextPage } from "next";
import Head from "next/head";
import fs from "fs";
import { parseMarkdown } from "../components/parseMarkdown";
import { Articles } from "../components/Articles";
import { CardAbout } from "../components/cards/CardAbout";
import AboutInfo from "../assets/data/about.json";
import { useContext } from "react";
import { ThemeContext, ThemeContextProps } from "../context/ThemeContext";
import { Hero } from "../components/layout/Hero";

const Home: NextPage = ({ articlesSortedByDate }: any) => {
  const { theme } = useContext<ThemeContextProps>(ThemeContext);

  return (
    <div className={`home ${theme}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <div className="container grid grid-column-2">
          <section>
            <Articles articles={articlesSortedByDate} />
          </section>
          <section>
            <CardAbout {...AboutInfo} />
          </section>
        </div>
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const files = fs.readdirSync("posts");
  const articles = files.map((file) => parseMarkdown(file).metadata);
  const articlesSortedByDate = articles.sort((a, b) => new Date(b.date).valueOf() - new Date(a.date).valueOf());

  return {
    props: {
      articlesSortedByDate,
    },
  };
};

export default Home;
