import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import fs from "fs";

const Home: NextPage = ({ slugs }: any) => {
  return (
    <div className={"container"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>header</h1>

        {slugs.map((slug: string) => {
          return (
            <li key={slug}>
              <a href={"/blog/" + slug}>{slug}</a>
            </li>
          );
        })}
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const files = fs.readdirSync("posts");
  const slugs = files.map((filename) => filename.replace(".md", ""));

  return {
    props: {
      slugs,
    },
  };
};

export default Home;
